name: Check for utils resources update
on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday, see https://crontab.guru/#0_0_*_*_0

permissions:
  contents: write
  pull-requests: write

jobs:
  check-for-resources-update:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'vuejs/eslint-plugin-vue' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: pnpm
      - name: Install Packages
        run: pnpm install
      - name: Update
        run: pnpm run update-resources
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Updates resources
          branch: update-resources
          branch-suffix: timestamp
          title: Updates resources
